### PR TITLE
fix windows using wrong file name

### LINKED ISSUE #21: OS supported
Which OS does this library support? IIRC Windows doesn't allow replacing binaries at runtime because they get locked when a program uses them. 

My wild guess would be that `self_update` doesn't support Windows.

### PR DESCRIPTION
**Pull request by SirWindfield**
I just tested the crate under Windows and it fails because the updater can't find the binary name without the `exe` file extension.

Fixes #21.

### CODE REVIEW

File: src/backends/github.rs [hunk 1]
```diff
@@ -340,9 +346,10 @@ impl UpdateBuilder {
 
     /// Set the exe's name. Also sets `bin_path_in_archive` if it hasn't already been set.
     pub fn bin_name(&mut self, name: &str) -> &mut Self {
-        self.bin_name = Some(name.to_owned());
+        let raw_bin_name = format!("{}{}", name, EXECUTABLE_SUFFIX);
```
Comment (jaemk) [inline src/backends/github.rs]: could this check the `name` and only add the suffix when it's missing?

File: src/backends/github.rs [hunk 2]
```diff
@@ -340,9 +346,10 @@ impl UpdateBuilder {
 
     /// Set the exe's name. Also sets `bin_path_in_archive` if it hasn't already been set.
```
Comment (jaemk) [inline src/backends/github.rs]: mind adding a mention of bin name requirements for windows in this method's docs?

File: src/backends/github.rs [hunk 3]
```diff
@@ -13,6 +13,12 @@ use tempdir;
 
 use crate::{confirm, errors::*, get_target, version, Download, Extract, Move, Status};
 
+// Used to construct the real binary name on Windows.
+#[cfg(target_os = "windows")]
+const EXECUTABLE_SUFFIX: &str = ".exe";
+#[cfg(not(target_os = "windows"))]
+const EXECUTABLE_SUFFIX: &str = "";
```
Comment (LPGhatguy) [inline src/backends/github.rs]: If you're still pursuing this PR, you can use [`std::env::consts::EXE_SUFFIX`](https://doc.rust-lang.org/std/env/consts/constant.EXE_SUFFIX.html) instead of rolling your own constant for this.

File: src/backends/github.rs (hunk 1 above)
Comment (nbigaouette) [reply src/backends/github.rs]: I think it would make more sense to keep it like that. The `format!()` call should result in the same as code as `to_owned()` when the suffix is empty; the compiler is probably able to optimize this away since `EXECUTABLE_SUFFIX`/`std::env::consts::EXE_SUFFIX` are constants.

So I think the proposed code is clearer _and_ produces optimal machine code. Adding extra checks would complicate things without much benefit.

File: src/backends/github.rs [hunk 4]
```diff
@@ -340,9 +346,10 @@ impl UpdateBuilder {
 
     /// Set the exe's name. Also sets `bin_path_in_archive` if it hasn't already been set.
     pub fn bin_name(&mut self, name: &str) -> &mut Self {
-        self.bin_name = Some(name.to_owned());
+        let raw_bin_name = format!("{}{}", name, EXECUTABLE_SUFFIX);
+        self.bin_name = Some(raw_bin_name.to_owned());
```
Comment (nbigaouette) [inline src/backends/github.rs]: No need to convert `raw_bin_name` using `to_owned()` since it's already a `String`.  Since `raw_bin_name` is used on the next line I'd say a `.clone()` would show the intentions better.

File: src/backends/github.rs (hunk 1 above)
Comment (jaemk) [reply src/backends/github.rs]: That makes sense! I'm not as worried about allocations as I am that the this method will be called with the wrong string -- if you call `bin_name("my.exe")` on windows, will that result in `raw_bin_name == "my.exe.exe"` ?

Comment (nbigaouette) [reply src/backends/github.rs]: Good point!

Looking at #21 I realized that the `.exe` _can_ appear in the `bin_name()` call... So I simply used `bin_name("my.exe")` and it worked.

The `name` could always be filtered of the `.exe` before being concatenated with it again. Something like:
```
let raw_bin_name = format!("{}{}", name.trim_end(std::env::consts::EXE_SUFFIX), EXECUTABLE_SUFFIX);
```

I'm having trouble running my own Windows CI-built releases but I'll try it after...

**Comment by SirWindfield** [comment]
I didn't know that the constant existed. I will update the PR after my last exam next week.

**Comment by SirWindfield** [comment]
Sorry, I totally forgot about this PR! Should be all solved (hopefully!).

**Comment by jaemk** [comment]
thanks!

**Comment by jaemk** [comment]
released in 0.17.0
